name: '名正在想的博客'
author: '名正在想'
url: 'https://mingzzx.com/'
baseurl: ''
description: '一个杂物堆'
meta_description: '名正在想'
motto: '名正在想的博客'
#banner: （无）

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

markdown: kramdown

mathjax: true